import {
  Amaz,
  Amerp,
  Bayw,
  Bigs,
  Hob,
  Imit,
  Jam,
  JamLogo,
  JamScene,
  Jumanji,
  Lucy,
  Moralis,
  MoralisLogo,
  MoralisScene,
  MovieLogo,
  Mrs,
  Reven,
  Secona,
  Shrek,
  Spidey,
  SpideyLogo,
  SpideyScene,
  Ted,
  Titanic,
  TitanicScene,
  Tomb,
  Topgu,
  Wolf,
} from "../images";

export const movies = [
  {
    Movie:
      "https://ipfs.moralis.io:2053/ipfs/QmNtxfy9Mk8qLsdGnraHGk5XDim8ayR93krM24ETJEd2bG/media/0",
    Thumbnail: Titanic,
    Scene: TitanicScene,
    Logo: MovieLogo,
    Name: "Titanic",
    Description:
      "Titanic is a 1997 American epic romance and disaster film directed, written, produced, and co-edited by James Cameron. Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of the RMS Titanic, and stars Leonardo DiCaprio and Kate Winslet as members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage. Also starring are Billy Zane, Kathy Bates, Frances Fisher, Gloria Stuart, Bernard Hill, Jonathan Hyde, Victor Garber, and Bill Paxton.",
    Genre: "Romance, Drama",
    Actors: "Kate Winslet, Leonardo DiCaprio",
    Year: "1998",
    Duration: "3h 15min",
  },
  {
    Movie:
      "https://ipfs.moralis.io:2053/ipfs/QmNtxfy9Mk8qLsdGnraHGk5XDim8ayR93krM24ETJEd2bG/media/0",
    Thumbnail: Spidey,
    Scene: SpideyScene,
    Logo: SpideyLogo,
    Name: "Spiderman Homecoming",
    Description:
      "Peter Parker tries to stop the Vulture from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student.",
    Genre: "Action, Superhero, Comedy",
    Actors: "Tom Holland, Zendeya",
    Year: "2017",
    Duration: "2h 13min",
  },
  {
    Movie: "",
    Thumbnail: Jumanji,
    Scene: "",
    Logo: "",
    Name: "Jumanji",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie:
      "https://ipfs.moralis.io:2053/ipfs/QmWWnyCZwh8RVnamjeLhGmpYM2C3oDr3FzF7zgv5ur24z5/media/0",
    Thumbnail: Moralis,
    Scene: MoralisScene,
    Logo: MoralisLogo,
    Name: "Moralis Rap",
    Description:
      "Moralis serverless Web3 Dapps, is a beautiful music video that tells a touching story of how anyone can become a Web3 developer if they put their trust in the hands of the musically gifted team at Moralis. ",
    Genre: "Music Video",
    Actors: "Ivan Liljeqvist, Filip Martinsson, CTO Larsson",
    Year: "2021",
    Duration: "1min 2sec",
  },
  {
    Movie: "",
    Thumbnail: Wolf,
    Scene: "",
    Logo: "",
    Name: "Wolf Of Wallstreet",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Mrs,
    Scene: "",
    Logo: "",
    Name: "Mr and Mrs Smith",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie:
      "https://ipfs.moralis.io:2053/ipfs/QmSi84pJTjBXmXREN8NMRuRnK9oobYb8QcPZsXUj3GZr12/media/0",
    Thumbnail: Jam,
    Scene: JamScene,
    Logo: JamLogo,
    Name: "Jam Doughnut",
    Description:
      "In this masterpiece a wild Jay, endulges in flavorful jam doughnut. Be warned, this video is most certainly going to leave you craving for some sweets.",
    Genre: "Silent Mukbang",
    Actors: "Jay",
    Year: "2022",
    Duration: "1min 5sec",
  },
  {
    Movie: "",
    Thumbnail: Hob,
    Scene: "",
    Logo: "",
    Name: "Hobbit",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Shrek,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Reven,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Imit,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Topgu,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Lucy,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Bayw,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Tomb,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Amaz,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Bigs,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Secona,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Ted,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumbnail: Amerp,
    Scene: "",
    Logo: "",
    Name: "",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
];
